### ISSUE TITLE
[Bug] Field Validating Input 

### ISSUE THREAD

**Issue by tsv3tan** [daritelska-platforma/frontend#100]
Missing validating input in Phone number field 

![image](https://user-images.githubusercontent.com/75036229/110534786-2850f000-8128-11eb-816f-359925d5eaac.png)
![image](https://user-images.githubusercontent.com/75036229/110535151-939ac200-8128-11eb-8bff-ccace76bbe1a.png)

**Comment by kachar** [comment]
Live at https://podkrepi.bg/support
