### ISSUE TITLE
[Bug]Missing filed validation on Name field

### ISSUE THREAD

**Issue by tsv3tan** [daritelska-platforma/frontend#101]
![image](https://user-images.githubusercontent.com/75036229/110535301-c0e77000-8128-11eb-86ce-fe157b10da1c.png)

**Comment by kachar** [comment]
Live at https://podkrepi.bg/support

**Comment by tsv3tan** [comment]
I only see a rule for the minimum number of characters, but not letter validation. It still takes me to the next step even with numbers instead of letters.

![image](https://user-images.githubusercontent.com/75036229/110587205-0719ef00-817c-11eb-8178-3809a9f2ac66.png)
![image](https://user-images.githubusercontent.com/75036229/110587537-7db6ec80-817c-11eb-97ff-37247038aa7d.png)

**Comment by kachar** [comment]
It's probably a valid case but it's not really worth the effort at this point. It's not an easy fix, so I'll leave it in the backlog for a while.

**Comment by kachar** [comment]
I've done a minimum set of validation that excludes numbers or some special chars, but the list of ways to break it can be huge. This use case is not business critical for sending a inquiry in my opinion. Anyhow I've spent a bit of time on it.

Feel free to reopen when the validation becomes business critical.
Keep in mind that the frontend validation is not protective enough and won't ever be sufficient.

Update is now delivered to production.
