### ISSUE TITLE
[Bug]Missing scheme in mobile view

### ISSUE THREAD

**Issue by tsv3tan** [daritelska-platforma/frontend#105]
![image](https://user-images.githubusercontent.com/75036229/110539409-e2972600-812d-11eb-8743-19c663b93121.png)

**Comment by kachar** [comment]
@tsv3tan This is expected behaviour as the current scheme is not responsive and renders too small to read on a mobile device with `xs` resolution.

Closing this one as no further action is expected, until we get a fully responsive svg
