### ISSUE TITLE
[Edit] To remove "Модел за самоиздръжка"

### ISSUE THREAD

**Issue by anikolova-bg** [daritelska-platforma/frontend#106]
To remove "Модел за самоиздръжка" from this page https://podkrepi.bg/about-project. We were talking since we did not have the final decision on the business model, better not to have it on the website yet. :)

**Comment by kachar** [comment]
![image](https://user-images.githubusercontent.com/893608/110646817-f12e1d80-81bf-11eb-9dcd-9b65b9249940.png)

**Comment by kachar** [comment]
Deployed on production
