### ISSUE TITLE
[Bug]Not working "Send" button to the contact form

### ISSUE THREAD

**Issue by tsv3tan** [daritelska-platforma/frontend#112]
1. Go to "https://podkrepi.bg/contact"
2. Fill the contact form
3. Click on the button "Send"
4. Error - Nothing is happening

Expected result - Show notification of sent message
Expected result - Received an email for the sent message

![image](https://user-images.githubusercontent.com/75036229/110758839-a2cb5e00-8255-11eb-8d3c-36805ed3125b.png)

**Comment by kachar** [comment]
Contact form is not yet functional as there is no backend attached, thanks for reporting
