### ISSUE TITLE
[Bug] Error in the console failed to load manifesto

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#128]
**Describe the bug**
In the console there is an error:
Failed to load resource: the server responded with a status of 401 https://podkrepi.bg/site.webmanifest

**To Reproduce**
When loaded, the site gives the error in the console

1. Go to 'podkrepi.bg'
2. Click on 'Inspect Element' anywhere
3. Check the console

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/62711773/111814920-bc1e7b00-88e3-11eb-8838-64491d61e8b9.png)

**Desktop (please complete the following information):**

- OS: MacOS BigSur 11.2.3
- Browser Opera GX
- Version LVL2 (core: 73.0.3856.400)

**Comment by kachar** [comment]
This problem is caused by the http password that we still require in order to access the website.

Once the password is gone, this problem will be gone as well

**Comment by kachar** [comment]
This should be OK now
