### ISSUE TITLE
[Feature] Create social media profiles and add dummy links

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#129]
**Is your feature request related to a problem? Please describe.**
On the bottom of the page there are social media links. Fill in dummy ones to check the redirects.

**Comment by kachar** [comment]
Once the social accounts are ready we'll update those links and test them.
There's no point in testing youtube links as the dev effort will be higher than the gain.

**Comment by kachar** [comment]
This has been done since #168
