### ISSUE TITLE
[Bug] Remove "Регистрация на сдружение Февруари 2021" from upcomming

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#130]
**Describe the bug**
Remove "Регистрация на сдружение Февруари 2021" from Upcomming tasks as it is stated above: "Регистрирахме сдружение в обществена полза (19.02.2021)"

**To Reproduce**

1. Go to 'https://podkrepi.bg/about-project'
2. Scroll down to 'Какво предстои'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/62711773/111816438-87abbe80-88e5-11eb-8e83-b8d70a7a8028.png)

**Comment by Svetlina89** [comment]
Timeline will replace the info above.
