### ISSUE TITLE
[Info Site] Add "Общи условия" and link it in the support page

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#131]
When going through the support page you encounter "Съгласявам се с Общите условия" but there are no "Общи условия" links. This is linked to https://github.com/daritelska-platforma/frontend/issues/94

**Comment by ani-kalpachka** [comment]
The page is implemented and linked in 'Support' form:
https://podkrepi.bg/terms-of-service
![image](https://user-images.githubusercontent.com/14351733/120529380-1c9e5e00-c3e5-11eb-9b88-a726768751e4.png)
We can close this issues.
