### ISSUE TITLE
[Bug] Missing hackaton in the BG version of about-project

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#132]
**Describe the bug**
While in the English version there is a hackaton: "Hackathon - 11,12,13 March" but its not in the BG version

**Screenshots**
![image](https://user-images.githubusercontent.com/62711773/111820831-9ea0df80-88ea-11eb-9c63-44dc3d6f58bd.png)
EN

![image](https://user-images.githubusercontent.com/62711773/111820860-a8c2de00-88ea-11eb-93f5-dac4e3aa58f1.png)
BG

**Comment by Svetlina89** [comment]
We should remove hackathon from timeline, because we don't have it.
