### ISSUE TITLE
[Bug] About us in both languages links to the homepage and not the *for now* dummy pages

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#133]
**Describe the bug**
In both languages the destination is set to the homepage.

**To Reproduce**

1. Go to 'podkrepi.bg' or 'podkrepi.bg/en'
2. Click on 'About us' or 'За нас'
3. See error

**Expected behavior**
Enter the pages 'About us' or 'За нас'

**Comment by Svetlina89** [comment]
We don't have the page yet, maybe we should remove the link to homepage.
