### ISSUE TITLE
Support us missing volunteer specialist areas

### ISSUE THREAD

**Issue by swolf86** [daritelska-platforma/frontend#145]
![image](https://user-images.githubusercontent.com/75036745/113493459-58956f80-94d7-11eb-8cb7-606c9e0e505f.png)
Missing: 
Design
PM
Devops? 
Finances and Accounts
Lawers

**Comment by kachar** [comment]
![image](https://user-images.githubusercontent.com/893608/113542868-dba8e980-95ed-11eb-8a34-fcd57eeac336.png)
