### ISSUE TITLE
[Bug] Different fonts in bg infographic svg file

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#157]
**Describe the bug**
Some of the infographic svg texts are embed fonts instead of curve paths

**To Reproduce**

1. Go to index page in bulgarian language
2. Scroll to the infographic
3. See different fonts in the same svg image

**Expected behavior**
Have the same fonts in all labels

- [x] bg / en versions of the svg
- [x] desktop / mobile svg images

**Screenshots**

![image](https://user-images.githubusercontent.com/893608/113999611-dc968100-9862-11eb-88a8-884578bb06e2.png)

**Comment by kachar** [comment]
Related to #154 and #124

**Comment by swolf86** [comment]
The font is Montserrat Medium and Bold
Attached curves svgs - BG and EN
[info graphics.zip](https://github.com/daritelska-platforma/frontend/files/6278521/info.graphics.zip)
