### ISSUE TITLE
[Bug] Homepage Banner About us button text wrapping

### ISSUE THREAD

**Issue by dimitur2204** [daritelska-platforma/frontend#160]
**Describe the bug**
The text on the hero banner "About the project version on the EN version wraps on two lines"

**To Reproduce**
Steps to reproduce the behavior:\
1. Go to '/en'
2. See the about button

**Expected behavior**
The text in the button does not wrap and it looks as the support us button

**Screenshots**
![image](https://user-images.githubusercontent.com/61479393/114070997-49cd0500-98a9-11eb-8c73-6c23ced0e7df.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 
- Version Version 89.0.4389.114

**Additional context**

**Comment by kachar** [comment]
Will be fixed with #164

**Comment by kachar** [comment]
On master
