### ISSUE TITLE
[Bug] English version of "About project" diagram has shliokavica 

### ISSUE THREAD

**Issue by DanielTakev** [daritelska-platforma/frontend#171]
**Describe the bug**
The English version of the "About project" diagram has a Bulgarian words "Daritelska platforma", written in Latin letters.

**To Reproduce**
Open the English version of "About project" page:
http://dev1.podkrepi.bg/en/about-project

**Screenshots**
Attached bellow.

**Desktop:**
- OS: MacOS Catalina 10.15.7
- Browser: Chrome v. 89

<img width="1320" alt="Bug_English_version_shliokavica" src="https://user-images.githubusercontent.com/56965899/115205428-38ce9000-a102-11eb-822f-67f1e6776bd7.png">

**Comment by ani-kalpachka** [comment]
@polibb, I think this issue is no longer valid since the graphic on https://podkrepi.bg/en/about-project is changed and its translations are correct:

![image](https://user-images.githubusercontent.com/14351733/120905304-ea496680-c659-11eb-90d0-5fcac258cdb4.png)
