### ISSUE TITLE
[Bug]https://dev1.podkrepi.bg/en/about leads to bulgarian text

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#182]
**Describe the bug**
The about page when in English is in Bulgarian.

**To Reproduce**

1. Go to 'https://dev1.podkrepi.bg/en/about'
2. See error

**Expected behavior**
English page

**Comment by kachar** [comment]
Duplicate of https://github.com/daritelska-platforma/frontend/issues/165

**Comment by atomov93** [comment]
Not the same. The page is not translated. #165 is font changes.
