### ISSUE TITLE
[Bug] Translate about project in English

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#199]
The section "What has been done already" of about project page is only translated in bulgarian

https://podkrepi.bg/en/about-project

We need english translation and extraction of the translation keys in `about-project.json` file

![image](https://user-images.githubusercontent.com/893608/119940775-5a8c2400-bf98-11eb-891a-f748233c3cf0.png)

**Comment by arthas168** [comment]
Starting on it

**Comment by arthas168** [comment]
PR up with one small question from my side - https://github.com/daritelska-platforma/frontend/pull/210
