### ISSUE TITLE
[Bug]White space Validation in phone number firld

### ISSUE THREAD

**Issue by tsv3tan** [daritelska-platforma/frontend#219]
1. Go to 'https://podkrepi.bg/support'
2. Click on 'phone field'
3. Enter phone number with white spaces in front of the number, the back of the number or somewhere else

**Expected behavior**
To autoclear white spaces in the filed

**Screenshots**
![image](https://user-images.githubusercontent.com/75036229/120709849-0ddba800-c4c6-11eb-95cd-d6003ca66e57.png)

**Comment by kachar** [comment]
Closed with https://github.com/daritelska-platforma/frontend/commit/11d39e34663c5d368b8fd400fcd54c3d4f1b76ff 

Also the email field is now trimmed so no whitespace messes with the validation https://github.com/daritelska-platforma/frontend/commit/11b9aa291a7b84ea17e807d33a863e22c6ee2e47
