### ISSUE TITLE
[Bug] Contact form backend phone validation does not match frontend validation

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#228]
**Describe the bug**
Frontend validation supports spaces in the phone number, backend validation does not support spaces and throws error.

**To Reproduce**

1. Send request

```shell
curl --request POST \
  --url http://localhost:5000/api/v1/contact \
  --header 'Content-Type: application/json' \
  --data '{
	"firstName": "John",
	"lastName": "Doe",
	"email": "test@example.com",
	"company": "",
	"phone": "02 222 333 444",
	"message": "test test test",
	"terms": true,
	"gdpr": true
}'
```

2. See error

```json
{
  "statusCode": 400,
  "error": "phone: 02 222 333 444 does not validate as phone",
  "validation": [
    {
      "field": "phone",
      "message": "phone: 02 222 333 444 does not validate as phone",
      "validator": "phone",
      "customMessage": false
    }
  ]
}
```

**Expected behavior**
Send the request successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/893608/120775779-35fdf200-c52c-11eb-9c07-eba428bbb33b.png)

**Comment by kachar** [comment]
Alternative solution might be to trim all whitespace from the phone number **before** it is sent to the backend.

I personally prefer this solution as we don't need the whitespace in the final db record

**Comment by tanyogeorgiev** [comment]
I'll prefer to trim/remove whitespace while user type in the input control.

**Comment by kachar** [comment]
@tanyogeorgiev Recently it was requested to allow users to add spaces in their phone numbers so they are not confused by the invalid number warning :man_shrugging: 

I guess if we take the spaces out on input we're gonna skip a whole shelf of whitespace problems.

I'll update the issue to reflect the statement above, thanks for the suggestion
