### ISSUE TITLE
SSR doesn't work for i18n

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#37]
The server renders plain non-translated objects on first request. Then the client renders the i18n which causes a flicker

```html
<title>nav.login</title>
```

**Comment by kachar** [comment]
Waiting for the i18n + next.js 10 to be supported at https://github.com/isaachinman/next-i18next/issues/869

**Comment by kachar** [comment]
There's a new beta of `next-18next` we we might bump this task up

https://github.com/isaachinman/next-i18next/blob/2640dc4fc1234b286e7b690bcb338c23329c0438/README.md

**Comment by StanislavSt** [comment]
@kachar Looks like next-i18next v8.0.0 is out  - https://github.com/isaachinman/next-i18next/releases/tag/v8.0.0.
Time to fix this bug ?
