### ISSUE TITLE
Right align nav menu and move locale switcher

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#52]
- to be combined with the right user avatar grid
- move `LocaleSwitcher` component to navbar

**Comment by vikinatora** [comment]
Between 960 and 1270px screen width the buttons for login/register are not visible
![image](https://user-images.githubusercontent.com/29047760/108897665-054e1880-761f-11eb-99be-be95e7fb3ae0.png)

**Comment by kachar** [comment]
@vikinatora Yeah, that is expected behavior, it looked okay when I was doing it initially

Any ideas are welcome
