### ISSUE TITLE
Create animated pie chart for homepage

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#55]
A great suggestion from the community was to use nivo.rocks as a react graph component lib

- https://nivo.rocks/ (https://github.com/plouc/nivo) based on d3
- Pie chart from https://nivo.rocks/pie
- Another sample of animated donut chart http://bl.ocks.org/dbuezas/9572040

We can play around with other charts beside pie after the initial version

Actual chart data can be found in the [wireframes](https://www.figma.com/file/IGERJuRUhZohuxq5b3O73w/Podkrepi.bg-Wireframes?node-id=718%3A0)

**Comment by Nikola-Andreev** [comment]
I can take the task tonight. But if there are other candidates , feel free to implement it.

**Comment by Nikola-Andreev** [comment]
![Screenshot (651)](https://user-images.githubusercontent.com/19424332/108961249-5a1d7d80-7677-11eb-93d5-7a889e31d856.png)

This is how it looks now on my local branch, but they are 2 problems:
1. If we insist the chart to be animated, maybe we have to use the another library like [highchart](https://api.highcharts.com/highcharts/series.pie.animation). I couldn't find an animation option with [nivo/pie](https://nivo.rocks/pie).
2. I am facing issues with making the pie responsive, the `ResponsivePie` pointed in the documentation is not showing on the screen with the current configuration. I will investigate this further tonight.

**Comment by kachar** [comment]
I've researched a bit and found this codesandbox example of hover animation on a pie chart

https://codesandbox.io/s/nivo-website-9yrvz?file=/src/pages/pie/index.js

Please check it out - if we can achieve that it can be sufficient for the initial release

https://user-images.githubusercontent.com/893608/108965046-fc902d80-7684-11eb-88a6-c79c4ad5d70a.mp4

**Comment by kachar** [comment]
We can also add a metric of all people as a big number in the middle if not too hard to be achieved.
https://nivo.rocks/storybook/?path=/story/pie--adding-a-metric-in-the-center-using-a-custom-layer

**Comment by Nikola-Andreev** [comment]
Thanks a lot @kachar , i will apply the changes tonight.

**Comment by Nikola-Andreev** [comment]
Damn, can't do the animation because the functionality is not released yet:
https://github.com/plouc/nivo/issues/1326
