### ISSUE TITLE
Create page "Contacts"

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#67]
https://www.figma.com/file/IGERJuRUhZohuxq5b3O73w/Podkrepi.bg-Wireframes?node-id=278%3A0

![Contact us](https://user-images.githubusercontent.com/893608/109160812-f3838700-777e-11eb-9d6d-dd727683e955.png)

**Comment by kachar** [comment]
@ani-kalpachka Draft of the integration has been started on branch `contact-page`

https://github.com/daritelska-platforma/frontend/compare/contact-page?expand=1

You can continue the effort if you'd like

**Comment by ani-kalpachka** [comment]
@kachar Started working on the task.
