### ISSUE TITLE
Add additional details to Support us page

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#69]
https://www.figma.com/file/IGERJuRUhZohuxq5b3O73w/Podkrepi.bg-Wireframes?node-id=245%3A0

![Support us](https://user-images.githubusercontent.com/893608/109161030-41988a80-777f-11eb-88ee-0e6c3ef69081.png)

**Comment by dimitur2204** [comment]
Should we use a slider/carousel library such as https://swiperjs.com/react or slick ? @kachar

**Comment by kachar** [comment]
At the moment I don't see the supporters logos carousel as mandatory for the initial public release as we don't have any logos.

Let's wait a bit with the carousel.

On the technical part - swiperjs looks like an awesome lib to be used.

**Comment by kachar** [comment]
I'm closing this one as the actual support us page looks totally different from this mockup created almost two months ago

![image](https://user-images.githubusercontent.com/893608/113755480-08a5eb00-9719-11eb-9b61-792d7c523205.png)
