### ISSUE TITLE
Language button to be one, not as a drop-down.

### ISSUE THREAD

**Issue by anikolova-bg** [daritelska-platforma/frontend#88]
To mak the language switch button as one button only, which shows the other available language.

**Comment by kachar** [comment]
@anikolova-bg If I get that correctly we need to place EN button on the bulgarian version and BG button on the english version?

Now the button shows the currently active language

**Comment by anikolova-bg** [comment]
Exactly. :)

**Comment by kachar** [comment]
Done!
