### ISSUE TITLE
Home page banner corrections

### ISSUE THREAD

**Issue by anikolova-bg** [daritelska-platforma/frontend#89]
- [x] The button text and size to be bigger.
- [x] To move the buttent up.
- [x] To make the banner photo fit in the desktop screen).
- [x] On loading the banner text appears with different font.

**Comment by kachar** [comment]
@ani-kalpachka As I see #96 covers some of the points above, do you mind marking the checklist items from this issue :heavy_check_mark: 

If all of these are done, please close the issue :bow:
