### ISSUE TITLE
[Info site] Privacy Policy and Terms and Conditions are missing

### ISSUE THREAD

**Issue by rkgeorgiev** [daritelska-platforma/frontend#94]
Privacy Policy and Terms and Conditions are missing from the Info website, even thought you are marking that you are agreeing with the Terms and Conditions upon singup.

![image](https://user-images.githubusercontent.com/18218058/109970565-e249f580-7cfd-11eb-83ba-5e4779696c34.png)

I guess the Legel team is working on those ?

**Comment by kachar** [comment]
@rkgeorgiev Unfortunately still don't have the content for those pages.

Anyhow at the moment the submission of the form doesn't store any data anywhere, as there's no backend whatsoever :joy_cat:

Thanks for bringing that up

**Comment by rkgeorgiev** [comment]
> @rkgeorgiev Unfortunately still don't have the content for those pages.
> 
> Anyhow at the moment the submission of the form doesn't store any data anywhere, as there's no backend whatsoever 😹
> 
> Thanks for bringing that up

I have asked the Legal team in Discord if someone is working on that. Hopefully a discussion will follow about it, since I believe its quite important.

**Comment by kachar** [comment]
Url to privacy policy document https://docs.google.com/document/u/1/d/1J4koWHP3MX00zffCNhjs1sAwPixFcd9k/edit?usp=drive_web&ouid=101217799053638702478&rtpof=true

**Comment by kachar** [comment]
Url to privacy policy document https://docs.google.com/document/u/1/d/1J4koWHP3MX00zffCNhjs1sAwPixFcd9k/edit?usp=drive_web&ouid=101217799053638702478&rtpof=true
